### ISSUE TITLE
Complicated paragraphs as of 1/22/2021

### ISSUE THREAD

**Issue by kbuzard** [kbuzard-SU/gradualism#61]
From @MatthewRGonzalez :
1. 304: I need some more description on what the issue is here (I don't understand all your codes, so I don't know what I should be paying attention to)
2. 719.4: My best interpretation for the 10lbs vs. 15 lbs thing in Torquay rests on the placement of "each" in the two different paragraphs. So that the line about "not over 10 pounds" means that within the 15+ pound container, there might be multiple smaller containers that are each less than 10 pounds. So the categories should be (and these may need to be split for herring and mackerel given what's in geneva 47) "
    - Herring, whether or not boned: In bulk or in immediate containers weighing with their contents over 15 pounds each and in immediate containers containing each not over 10 pounds of herring, net weight
    - Herring and mackerel whether or not boned: In bulk or in immediate containers weighing with their contents over 15 pounds each and not in immediate containers containing each not over 10 pounds of herring, net weight
    - Herring and mackerel, other
Here, my understanding is the herring and mackerel have to be split into two because there are different duties in Geneva47. 
3. 1108,1109, 1119 (all have similar issues, unsure about grouping items here): can you tell me which rounds I need to look at to see what the trouble is?

From @Zeyuan-Xiong :
1. 1530e: I created a sheet in the OneDrive document with a proposal for how to do this. I filled in some of the tariff values as I went, but I didn't follow them through the divergences in most cases and I didn't check them very carefully because I CAN'T SEE STRAIGHT ANYMORE. ;-)
    - Let me know what you think...
2. 202a: I see a lot of complications here, but I can't tell clearly which ones you've solved and which questions remain. Could you give me a description of the problem you're having? Either in writing or in-person would be fine.
3. 339: I'm again not clear on what the specific issue is. Can you point it out to me?
4. 397: I had a hard time understanding your notes. This seems like a big one that will take some serious work to reconcile. Again, please point out what the issues are and I'll see what I can do.

**Comment by MatthewRGonzalez** [comment]
@kbuzard Thank you so much for taking the time to look into these! Here are my thoughts/responses. Please let me know if I can describe anything in more detail.

> 304: I need some more description on what the issue is here (I don't understand all your codes, so I don't know what I should be paying attention to)

My confusion here is mostly related to the development of "Bars and billets, whether solid or hollow", across rounds:

In the excel document, there is a section of this paragraph highlighted in light green, beginning with "Bars, whether solid or hollow (except hollow bars and hollow drill steel valued over 4 cents per pound): Valued not over 1-1/2 cents per pound". These rows come from the Dillon round. 

Originally, the entries from torquay groups bars and billets. For example: 
"Bars and billets, whether hollow, or solid, valued per pound: Not over 1-1/2 cents".

Bars and Billets are also grouped together in S-H as well. But these two entries (Bars vs. Billets) are slit up in Dillon. A potential solution to this is to edit our descriptions so we have entries for bars only, and other entries for billets only. Then we code each with the same rate for schedules in which they are grouped, and then separately when the two are separated. In this case I believe we would end up having to add many additional lines here.


> 719.4:

This makes sense for now, My issue was with the Torquay description. I'll work to develop this section entries based on your proposed structure and update later on. 


> 1108,1109, 1119

I'll begin with 1108,1109:

- S-H different tax rates for different valuations for pound
- Geneva1 and Torquay tax woven fabrics weighing not over 4 oz, Regardless of value
-  Then in Dillon, items are taxed at different rates based on value or whether or not they are with warp. There is also a difficult section related to "Hand woven fabrics with a loom... for religious orders"

I think this can be resolved by adding more lines: Where we would have something like. I'm not very confident here..

- woven fabrics not weighing over 4 lbs.
     - Hand made
          - Further specifications based on value
     - With warp
          - Further specifications based on value
     - Other
          -  Further specifications based on value
- woven fabrics weighing over 4 lbs.
     - Hand made
          - Further specifications based on value
     - With warp
          - Further specifications based on value
     - Other
          -  Further specifications based on value

> p.1119:

This is the description of how the paragraph should be taxed, which is difficult regarding the complications in p.1108/1109:

> p.1119. Tapestries and upholstery goods (not including pile fabrics), in the piece or otherwise, wholly or in chief value of wool, shall be subject to the applicable rates of duty imposed upon woven favrics of wool in paragraphs 1108 or 1109

**Comment by kbuzard** [comment]
I think this is the right solution for 304, even if it means MORE lines

> A potential solution to this is to edit our descriptions so we have entries for bars only, and other entries for billets only. Then we can code each with the same rate in schedules where these descriptions/items are grouped, and then separately in rounds when the two are not grouped. In this case I believe we would end up having to add many additional rows.

On 1108 and 1109: I think the breakdown you've proposed makes sense. Why don't you take a shot at it, let me know when you're done, and then I'll take a look at it.

On 1119, I think you will have to repeat the structure of 1108/1109 :(

**Comment by MatthewRGonzalez** [comment]
Will do! I'll try to resolve these this evening. Also, I believe that was able to resolve p.719.4 based mostly on your recommendation above. 

I'm aiming to submit a progress report tomorrow after I clean up some notes. I'll dedicate a section towards paragraphs like these that have had to be changed.

**Comment by MatthewRGonzalez** [comment]
@Zeyuan-Xiong @kbuzard I've developed some solutions to p.719.4,5; p.304; p.1108,1109, in the "New entries" sheet. 

A couple of thoughts: 
- There are "Provided" sections in p.304 that I still need to check over to make sure I'm not missing anything.
- **Victor**, There's a difference in tax boundaries in p.1108,1109; I'm using 1.25 instead of 1.27. I believe that we have already discussed this feature in a comment thread from "Main Data: G2117", but I'd just like to highlight this change.

**Comment by kbuzard** [comment]
- p.719: looks good.
- p.304
    - "Steel" is mispelled in several places as "steal" (being able to spot this is one of the more important perks of being a Steelers fan)
    - I didn't realize this before, but bars are created from billets (see conclusion on [this page](https://www.techsteel.net/what-is-the-difference-between-steel-billets-and-steel-bars)). So I think the "including bars" should be taken out from the billets half of the lines. I'm not sure that billets can be "hollow drill" either--I've spent some time Googling it and haven't found anything definitive. There was a journal article from 1957 that I didn't follow up on though...
        - Further, Billets are listed separately with ingots in Geneva56, and Hollow bars and hollow drill steel having its own separate section. I'm thinking this means we probably don't need the hollow drill steel under billets either. If you need me to, I can ask a friend who worked high up at ArcelorMittal up until recently. 
    - Is the "provided further" line on hollow bars and hollow drill still properly incorporated into the specific tariffs for Smoot Hawley?
- p.1108/1109: Should, for instance, rows 482 and 483 also have the "NOT WITH WARP wholly of cotton or other vegetable fiber" (and similarly below)?

**Comment by MatthewRGonzalez** [comment]
> "Steel" is mispelled in several places 

Yikes- Resolved.

> Further, Billets are listed separately with ingots in Geneva56, and Hollow bars and hollow drill steel having its own separate section.

This seems to be good justification for removing the hollow drill/bar from the billet subsections. I'll do that now. If asking your friend isn't difficult, I think it would help to remove any lingering doubt.

> Is the "provided further" line on hollow bars and hollow drill still properly incorporated into the specific tariffs for Smoot Hawley? 

Resolved, but an interesting note here:

- This provision is in S-H, but Geneva1-Torquay each include a provided section that indicates that there is no additional duty on hollow drills/bars. Then Geneva56 adds uses the provision and adds an additional .375/ lb on all hollow drills/bars. This is now reflected in my proposed entries. 

> Should, for instance, rows 482 and 483 also have the "NOT WITH WARP wholly of cotton or other vegetable fiber" (and similarly below)?

Is the proposal here to add "Wholly of cotton or other vegetable fiber" to the descriptions? Or are you thinking that there's an issue in the "NOT WITH WARP" vs. "WITH WARP" entries? Regardless, I have updated the description to include "wholly of cotton etc..."

**Comment by kbuzard** [comment]
I just sent an email to Matthieu. It will be interesting to see what he says, especially since he's a native French speaker and this is confusing enough in English! I'm guessing he probably worked a lot in English though (he ran steel mills in three or four different countries in Europe).

That thing on the "provided" note in p.304 IS really interesting. Let's make sure to flag that somehow to go back and look at it in the analysis. Thanks for pointing it out.

> Is the proposal here to add "Wholly of cotton or other vegetable fiber" to the descriptions? Or are you thinking that there's an issue in the "NOT WITH WARP" vs. "WITH WARP" entries? Regardless, I have updated the description to include "wholly of cotton etc..."

My reading of the correspondence between Dillon and what you have in the "New" entries sheet is that what are now rows 475-477 all make up the one category in Dillon for religious orders "NOT WITH WARP wholly of cotton or other vegetable fiber." If that's right, then they should all have the same description except for the $ cutoffs (and likewise 478-480)

**Comment by MatthewRGonzalez** [comment]
> they should all have the same description except for the $ cutoffs 

Understood, and I agree- This should now be resolved.

**Comment by Zeyuan-Xiong** [comment]
Hi all, I was examing paragraph 1108 of Dillon round (compared to Torquay and S-H), to be honest, I do not think the coding is totally wrong, but it does create some weired result in statistic perspective. I am not very sure how to deal with this new product in the Dillon round. Could you please also take a look at this and feel free to comment, thanks! @kbuzard @MatthewRGonzalez

**Comment by MatthewRGonzalez** [comment]
@Zeyuan-Xiong I'm looking now. Which weird result do you mean? I'm guessing its something like row 2134 where there's a tax increase from Torquay to Dillon?

**Comment by Zeyuan-Xiong** [comment]
Yes, exactly, the increase in tax rate, and also it looks like the increase is only for the new product in Dillon round.

**Comment by MatthewRGonzalez** [comment]
I'll need to look at this more. Although, if we consider row 2143, (Corresponding to an entry in 1109), we also see an increase and this specific row seems to be coded accurately.

**Comment by MatthewRGonzalez** [comment]
According to the note in Torquay p.1108: 

> "The United states reserves the right to increase the ad valorem part of the rate applicable to any of the fabrics provided for in item 1108 or 1109(a) of this Part to 45 per centum ad valorem on any of such fabrics which are entered in any calendar year in excess of an aggregate quantity by weight of 5 per centum of the average annual production of similar fabrics. in the United states during the 3 immediately preceding calendar years."

This provision seems to be acted upon in this [proclamation](https://www.presidency.ucsb.edu/documents/proclamation-3225-amendment-proclamation-no-3160-relating-certain-woolen-textiles).

This might help to explain the AV increase that we see in row 2143. 

At this point, however, the rate increase in row 2134 and those similar still seems like an outlier to me, but is not be entirely out of the question.

**Comment by kbuzard** [comment]
From just looking at the data, I see the four lines where the specific went up the most also have the ad valorem go away. Although I thought the story was generally one of specific being converted to ad valorem, that doesn't seem to be happening in our data so far (maybe a future round), and here is one instance of the opposite thing happening.

For future use, in order to see the specific and ad valorem separately for a given paragraph, you can use this code
- av_1108 <- ad_valorem[which(ad_valorem$Paragraph=="1108"),]
- specific_1108 <- specific[which(specific$Paragraph=="1108"),]
To make this a little more readable, I need to go back into the data_cleaning program and have the id and Product columns kept in the specific and ad_valorem data sets

Looking at the complicated tariff in Dillon for this line--the ad_valorem didn't TRULY go away, or not completely because of the cap that involves an ad valorem tariff. Do either of you recall other lines that had this kind of "but not over" formulation? If this is the only one, then I think we can just make note of it. But if it's pretty common and not taken account of in our data, maybe we need to think harder about it.

**Comment by kbuzard** [comment]
My code shows that there are four lines in the current data file that don't have any tariff for Smoot Hawley or Dillon.

They are in paragraphs 368.c_18, 810, 1408, 1532.a

What do we need to do to resolve these? I think @Zeyuan-Xiong and I talked about one that might have to stay on hold for a while...

**Comment by Zeyuan-Xiong** [comment]
I was discussing with Matt the other day about this, in my opinion we should **delete** these four observations since they do not give any specific number for the tax rate, they are more like applied provisions for certain products under certain circumstances. It will be very inaccurate to give them a quantative interpretation given that all later rounds do not have specific value of tax rate for these four lines either.

**Comment by MatthewRGonzalez** [comment]
I think that this is definitely a judgement call. I'm providing an overview below to highlight the remaining issues and help with our decisions here:


For example, p.1532.a specifies rates for "glove trunks":
> "75 per centum of the duty provided for the gloves in the fabrication of which they are suitable"
- This item/rate is *only* mentioned in S-H, and not in any of the later rounds. 

p.1408 - envelopes
- I have spent some time trying to develop this section, envelopes are supposed to be taxed at the same rate as the paper which they are made from, but I'm having a lot of difficulty discerning which types of papers can be made into envelopes, it turned into a more difficult section than I originally intended.
With this said, It is still possible to expand this item into lines saying "envelopes for paper of type __," with their specified rate, though this probably requires assumptions regarding which papers fall into this "envelope" section.

p.810 - bottles
- Again, this can potentially be expanded, and has been discussed. I'll see what I can do here.

p.368.c_18: 

The rate specified is:
> no assembly or subassembly shall be subject to a greater amount of duty than would be borne by the complete movement, mechanism, device, or instrument for which suitable

- This rate is difficult because it seems to specify a "maximum" rate and just seems to be some additional provision for the items it relates to.

**Comment by kbuzard** [comment]
Thank @MatthewRGonzalez . This gives me a good idea of where we stand.

Would you look at the three round we haven't coded yet and see how the issues involving these lines play out going forward? I think we can make a better decision if we see the whole picture. It might also be a source of learning for the more general effort to add those three rounds.

**Comment by MatthewRGonzalez** [comment]
@kbuzard I've looked into our upcoming uncoded rounds and am posting my findings below:

**p.1532 (Glove Tranks)**

- I realized this item is **Tranks**, not trunks. Unfortunately, this didn't lead to any new insights.
- Based on the structure of the Tariff act of 1962, I'd expect it to be around item no. 704. However, I have not found it in the Tariff act of 1962, Kennedy or Tokyo.

**p.1408 Envelopes:** 

Rates described in TA1962, Kennedy and Tokyo, (item no. 256.42) as:

- Not bordered/embossed etc..

- Boredered embossed etc 

If the second column of TA1962 provides the rates for S-H, I think I can actually make sense of how we can code envelopes in S-H. It basically becomes the rates from S-H p.1407.a + x, where x is the "In addition thereto" rate described in S-H that paragraph. I'll try to code this in the "New Entries" sheet and keep you updated.

**p.810 Bottles**

- Not in TA1962, Tokyo or Kennedy.  It seems that there are might be a shift towards taxing based on the containers's volume, but this is just a guess.

**368.c_18**
- Still exists in TA 1962, Kennedy, Tokyo. coded as item no. 720.75

**Comment by kbuzard** [comment]
How about in the Uruguay Round?

By far the funniest thing I've read all day:
> I realized this item is Tranks, not trunks. Unfortunately, this didn't lead to any new insights.

**Comment by MatthewRGonzalez** [comment]
*In Uruguay:*

- Glove Tranks: 
     - Not mentioned (would be around item no. 6116)

- Envelopes:
     - Slight change from previous rounds (Tokyo, Kennedy etc..). It seems that envelopes are not longer separated into the two entries, "Bordered or embossed..." vs "Not bordered or embossed."

- Bottles
     - Still not found (would be around chapter. 22). The structure is similar to previous rounds where tariff is applied to containers for certain items based on capacity volume

- 368.c_18
     - I think that this is still accounted for in 9114.80.30. 
     - In this round and previous rounds, it seems like our "missing" entry from note from S-H, and Torquay becomes a condition in later rounds, stating, "The total duty shall not exceed the duty for the complete movement"

**Comment by kbuzard** [comment]
Okay @MatthewRGonzalez , I think we can safely omit the glove tranks (man, that was an internet hole) from p.1532, making sure of course that we have a clear note saying that we did this and that it was because it was unclear how to code it and it doesn't show up in later rounds.

I don't think UR changes the plan for the envelopes or the bottles. Just let me know when you have that worked up and I'll take a look.

I'm really confused about p368c. Maybe we could schedule a brief video chat to work this out?

**Comment by kbuzard** [comment]
In the data as of last night, there are now a couple more lines that don't have any tariff.

Sched Product Paragraph id
3 17 355 980
3 1 368.c_18 1078
8 1 810 1889
14 1 1408 2443
15 17 1532.a 2866
15 12 1558 3035

Are these resolve-able?

**Comment by Zeyuan-Xiong** [comment]
I just fixed two of them. The remaining ones are:

368c_18
810
1408
1532a

These four lines just dont have explicit tax rates, they only have a statement or depending on other products' tax rates. So it will be inappropriate to just assign them a tax rates. So I still propose that maybe we could create a separate sheet called "special lines and provisions" to list out those statistically irregular lines (separate them from the main data set), so that we keep the completeness of the schedule and also will have a better looking statistical result.

**Comment by kbuzard** [comment]
Let's go ahead and add p.810 to the list of lines to drop

I wonder if we should just leave p1408 out as well. Just putting in this additional charge on the envelope without adding it to the base rate for the paper gives an artificially low tariff. Thoughts? @MatthewRGonzalez @Zeyuan-Xiong

**Comment by MatthewRGonzalez** [comment]
@kbuzard  Dropping these few rows makes sense to me. My only other though would be to apply the rates specified in in TA1962 for either bordered/decorated or plain envelopes to these S-H rows, but in my opinion using these rates instead wouldn't be authentic.

**Comment by Zeyuan-Xiong** [comment]
I agree with just dropping them or at least separate them from the main data file to avoid statistical inference bias.

**Comment by kbuzard** [comment]
Okay, @Zeyuan-Xiong, please create a separate sheet in the data file and move into it all the lines associated with paragraphs
- 368c_18
- 810
- 1408
- 1532a
